# 브랜치명 : [라벨명]/#[이슈번호]
branchName: '/issue-${issue.number}'

# branches 설정 사용(라벨 Prefix)
branches:
  - label: 'feat'
    name: 'feat'
  - label: 'fix'
    name: 'fix'
  - label: 'docs'
    name: 'docs'
  - label: 'style'
    name: 'style'
  - label: 'refactor'
    name: 'refactor'
  - label: 'chore'
    name: 'chore'
  - label: 'test'
    name: 'test'
  - label: 'perf'
    name: 'perf'
  - label: 'ci'
    name: 'ci'
  - label: '*'
    name: 'issue'
